In [1]:
#Importing files required for cleaning of outliers
import pandas as pd
import numpy as np

In [2]:
#Reading the dataset we have to remove outliers from and clean the data
train = pd.read_csv('train.csv')

In [3]:
#Only outliers replacing is required as the data set has no null values and duplicate values as studied in the EDA.
# Function to detect and replace outliers using the IQR method
def replace_outliers_iqr(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Replace outliers with the median of the column
        median = df[col].median()
        df[col] = np.where((df[col] < lower_bound) | (df[col] > upper_bound), median, df[col])
    return df

# Identifying numeric columns for outlier detection
numeric_columns = train.select_dtypes(include=['int64', 'float64']).columns

# Replacing outliers
data_cleaned = replace_outliers_iqr(train.copy(), numeric_columns)

# Checking the changes
data_cleaned.describe()

,age,balance,day,duration,campaign,pdays,previous
count,40000.000000,40000.000000,40000.000000,40000.000000,40000.000000,40000.0,40000.0
mean,40.470125,557.971150,16.017225,196.182175,2.167100,-1.0,0.0
std,9.503955,742.008028,8.278127,133.210021,1.286339,0.0,0.0
min,19.000000,-1818.000000,1.000000,0.000000,1.000000,-1.0,0.0
25%,33.000000,55.000000,8.000000,100.000000,1.000000,-1.0,0.0
50%,39.000000,407.000000,17.000000,175.000000,2.000000,-1.0,0.0
75%,48.000000,782.000000,21.000000,257.000000,3.000000,-1.0,0.0
max,70.000000,3216.000000,31.000000,632.000000,6.000000,-1.0,0.0

In [4]:
#Extracting the cleaned dataset which would be used for ML Model.
data_cleaned.to_csv('cleaned_file.csv', index=False)